### ISSUE TITLE
Feature request: Fix MC-881

### ISSUE THREAD

**Issue by bilde2910** [Gamealition/Titanic#2]
The issue [MC-881](https://bugs.mojang.com/browse/MC-881) is a bug related to boats and fall damage. Sit in a boat on water for a few minutes, then drive the boat onto some half slabs or, well.. onto something else than water and exit the boat. This will result in fall damage being applied to the player exiting the boat. I drove into soul sand and was instantly killed due to the fall damage that had accumulated. Normally, this wouldn't be noticed because when you exit a boat, you typically land in water, and the water nullifies the fall damage.

Is it possible to request some kind of fix for this? It is super frustrating to come home from a boat ride and park my boat on some slabs only to be instantly killed by fall damage. I would look into it if I was more knowledgeable about Bukkit, but I've never coded a Bukkit plugin before, so I'm not sure where to start.

**Comment by RoyCurtis** [comment]
I had a bit of difficulty reproducing this. It turns out that ToughBoats unintentionally fixes this issue _to a degree_.

The resync feature of ToughBoats cancels out the accumulated fall damage when it remounts the player on a new boat in the server-side position. The default resync time is 60 seconds, [but this could be lowered (against the config file's recommendation) to 30 or even 10 seconds to safely negate all fall damage](http://i.imgur.com/klsHvec.png).

But this is only a work-around. Now that I am able to reproduce the issue, I can try to fix it proper.

**Comment by bilde2910** [comment]
Ah, this was beyond my knowledge. What value would you consider safe to lower to? It's a personal server for friends, and we're only ever going to be 2 or 3 people online at any given time.

It's good to know that the issue is already partially fixed, even if unintentional. I can safely rest assured that boats no longer conspire to kill me.

**Comment by RoyCurtis** [comment]
I gave a very brief try with just 5 seconds, and it seems to work OK. I think the warning is just in-case the constant entity destruction, creation and teleportation causes lag but these days Spigot can handle that just fine, maybe even with dozens of people on boats.

So... I say lower it to five. It _should_ be safe.

**Comment by RoyCurtis** [comment]
I have implemented this in 7fd3169, built as release 1.5: https://github.com/Gamealition/ToughBoats/releases/tag/1.5-SNAPSHOT

I took a blunt approach to fixing this vanilla bug by negating all fall damage if the player is in a boat. This affects vanilla behavior as it means players can use boats to avoid fall damage in any situation.

I assume this would be sufficient; to try and negate only bugged fall damage would be more difficult. If you would prefer this, let me know.

Else, please enjoy! 1.5 comes with other fixes also. Thank you for the suggestion.

**Comment by bilde2910** [comment]
Thank you for implementing! Now I no longer have to worry about boats' player assassination plans! Finally I can put my indoors harbor to use :-)
